language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chadyuktech/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chadyuktech/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-755421375525"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY